version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fortuneteller
      TZ: Europe/Istanbul
    ports:
      - "3306:3306"
    networks:
      - db-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8080:80"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
